### ISSUE TITLE
We need x on circle, Movie LV 2!

### ISSUE THREAD

**Issue by maqtulio** [google/blockly-games#100]
https://github.com/google/blockly-games/blob/601b1bf1b8212af213ea87f0478516497e54666a/appengine/movie/template.soy#L232

Lv 2 can`t be solved if we are not able to change X on the circle to a fixed number.

**Comment by NeilFraser** [comment]
Confirmed.

This bug is a result of an older version of level 2 which didn't use x.

Note that if you solve level 1, the blocks carry over to level 2, which allows one to solve the level.

Fixed in the codebase.  The live version will be updated sometime soon.
