### ISSUE TITLE
Can blockly-game  show Python codes，now it show java codes

### ISSUE THREAD

**Issue by lyalove** [google/blockly-games#107]
many students study py ,this blockly-games is good for them.
if someone finish a game,it will show  blockly to java codes.
 but,i want it show the blockly to python codes.
can you trans them to python codes? or  a  switch i can select.

thks.

**Comment by NeilFraser** [comment]
As one progresses through the games, the learning path is designed to introduce the students to a curly-bracket language.  With the exception of Python, virtually all languages in use today are curly-bracket languages.  C, Java, JavaScript, PHP, Swift, and [dozens of other languages](https://en.wikipedia.org/wiki/List_of_programming_languages_by_type#Curly-bracket_languages) all share a common syntax.  Blockly's block shapes are designed to mimic (and eventually transition into) this syntax.

Consider this screenshot from the Pond game:
![screen shot 2019-01-29 at 11 53 05](https://user-images.githubusercontent.com/250480/51936255-9c9efe00-23bc-11e9-8791-cc34f177cf66.png)

Rewriting Blockly and Blockly Games to emulate a whitespace-based language (of which Python is the only currently popular example) would be a significant UI overhaul.
