### ISSUE TITLE
the & sign in ur languages cause a bug that interrupt the make command

### ISSUE THREAD

**Issue by elowes** [google/blockly-games#109]
![20190219163141](https://user-images.githubusercontent.com/8766034/53000878-4fb2c280-3464-11e9-95a4-f23d8cdfd713.png)

**Comment by NeilFraser** [comment]
Thanks, fixed (again).

That's the second time I've had to fix quotes in the 'ur' translation:
https://github.com/google/blockly-games/commit/79788e4b359e1ad68bfa54bd15bd51ab2319ab9f
