### ISSUE TITLE
Turtle.checkAnswer should check colors

### ISSUE THREAD

**Issue by tuukka** [google/blockly-games#11]
Turtle.checkAnswer currently doesn't check that the answer has the correct colors:
```// Pixels are in RGBA format. Only check the Alpha bytes.```
https://github.com/google/blockly-games/blob/master/appengine/turtle/js/turtle.js#L663

**Comment by NeilFraser** [comment]
We chose to ignore colours for a few reasons.  First, they are not important from a programming perspective.  Second, colour-blind students (10% of males) should not have to thrash around randomly looking for the right shade.  Third, students will often intentionally choose a different colour than expected just to be creative and we don't want to punish this.

**Comment by tuukka** [comment]
Good point about colour-blindness. Nevertheless, the task description currently sets the expectation of being able to pick yellow - perhaps it could ask for "a colour" instead of "yellow". Further, checkAnswer could check that a colour was chosen.

**Comment by masmangan** [comment]
I would agree with @tuukka and add that there is a difference between a) being creative and b) ignoring the requirements. Even a colour-blind or a completely blind programmer must be able to comply to requirements, by asking help  or learning the color codes  that can be easily integrated on the UI, as they are displayed by the code generator.
Also total color blindness is very rare (https://nei.nih.gov/health/color_blindness/facts_about). Carefully selected colours may help to overcome most, if not all, difficulties.
