### ISSUE TITLE
Update puzzles

### ISSUE THREAD

**Issue by gterzopoulos** [google/blockly-games#112]
Greeting and congrats about the project. I am interested in creating a mobile game with blockly game for educational and research purposes. Can levels for each game be edited so that a teacher for example to give certain levels to his students to solve?

**Comment by NeilFraser** [comment]
The level maps are defined here and are really easy to change:
https://github.com/google/blockly-games/blob/master/appengine/maze/js/maze.js#L114

Interactive help for each level is trickier.  The help contents are defined here:
https://github.com/google/blockly-games/blob/master/appengine/maze/template.soy#L116
And the triggers are defined here:
https://github.com/google/blockly-games/blob/master/appengine/maze/js/maze.js#L600
