### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by elowes** [google/blockly-games#115]
https://github.com/google/blockly-games/blob/893a542ce4e32792c2f88178ba49d40d2d067c37/appengine/turtle/js/answers.js#L158-L170

![image](https://user-images.githubusercontent.com/8766034/63913741-d4aa1480-ca63-11e9-96c8-d139e3ee45ef.png)

Two 360 for loops cause performance problems, and the page will be white for a while. If you have free time, please optimize this part of the code.

Thx.

**Comment by NeilFraser** [comment]
Can you describe a bit more how you recreate this performance issue?

I've tried executing the following code, with the speed slider set to maximum.  But it behaves as I'd expect with lots of drawing, not a white page.

<img width="806" alt="Screen Shot 2019-08-29 at 00 02 38" src="https://user-images.githubusercontent.com/250480/63917923-7e4fbe00-c9f0-11e9-8038-c0537a9e06d6.png">

**Comment by NeilFraser** [comment]
Oh, I see what you mean.  Just loading level 9 causes a one second white screen while the answer pre-computes, whereas loading level 1 or 10 has no such delay.  Got it.

Thanks, I'll look into this.

**Comment by NeilFraser** [comment]
Thanks for the report.  It's fixed in the codebase.  Next push to production servers will be in a month or so.
