### ISSUE TITLE
Just button show on Puzzle, Maze and Bird

### ISSUE THREAD

**Issue by viet1pro** [google/blockly-games#116]
All other can be run execpt Puzzle, Maze and Bird
The errror in console of Puzzle is:
`TypeError: g.g.gh is undefined`
The errror in console of Maze is:
`TypeError: g.Jt is not a constructor`
The errror in console of Bird is:
`TypeError: g.ov is not a constructor`

**Comment by NeilFraser** [comment]
Sorry about that, there was a missing include for Blockly.utils.colour.  Fixed:
https://github.com/google/blockly/commit/7653785ae6ffa96760e03c55cd10e13b856894fd

Just run `make deps` and everything should be good.  Thanks for the report!
