### ISSUE TITLE
Nothing is shown on Maze

### ISSUE THREAD

**Issue by kuaicha** [google/blockly-games#117]
The error info in console is：
Failed to load resource: net::ERR_FILE_NOT_FOUND
compressed.js:500 Uncaught Error: Missing require for Blockly.VerticalFlyout
    at Gc (compressed.js:500)
    at Object.h.zy (compressed.js:528)
    at Object.h.tf (compressed.js:524)
    at compressed.js:753

**Comment by NeilFraser** [comment]
This was fixed two weeks ago: https://github.com/google/blockly-games/commit/a570b784fb94c605518424d343bfe759146b320f

Just pull from GitHub, and rebuild.

**Comment by kuaicha** [comment]
Thanks a lot！
