### ISSUE TITLE
Possibility to disable Javascript demo for youngest kids

### ISSUE THREAD

**Issue by EricSeynaeve** [google/blockly-games#13]
For the youngest kids (7 y.), having a graphical programming language is great to start their adventures in programming.

However, showing the Javascript code is, IMHO, too advanced for this age bracket.

I'm looking at a way to make this optional. What is the input of the main developers ?

Regards,

Eric

**Comment by blockly** [comment]
A recent survey of software engineers working at Google showed that the
most common age to start programming (text-based) was 8 years old.  Showing
code to a seven year old should not have adverse effects.

What problems are you experiencing?

On 19 January 2015 at 12:45, EricSeynaeve <notifications@github.com> wrote:

> For the youngest kids (7 y.), having a graphical programming language is
> great to start their adventures in programming.
>
> However, showing the Javascript code is, IMHO, too advanced for this age
> bracket.
>
> I'm looking at a way to make this optional. What is the input of the main
> developers ?
>
> Regards,
>
> Eric
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/blockly-games/issues/13>.
>



-- 
Neil Fraser
https://neil.fraser.name

**Comment by EricSeynaeve** [comment]
I would expect these lines of code to be somewhat confusing to them.

On the other hand, I did use blockly games in the current incarnation and they didn't ask anything about the JavaScript. It seems they just ignored it ;-)

My experience with kids is from CoderDojo and thus Scratch. I'm very surprised to see that 8 year old kids would start working with text based programming. How was that survey made ?

Would you be open to have a toggle button for the code ? Not everyone would want to use Blockly for learning JavaScript. You can see a very first attempt in my clone.

Regards,

Eric

**Comment by NeilFraser** [comment]
> My experience with kids is from CoderDojo and thus Scratch.
> I'm very surprised to see that 8 year old kids would start
> working with text based programming. How was that survey made ? 

During their orientation classes, we used an online form to ask a hundred newly hired engineers "At what age/grade could you have written a program that prints 'Hello' and infinite number of times?"  The results matched the experiences of myself and my immediate coworkers.

Back in our day there was no graphical programming.  It was green text on a TV screen.  Rich kids had the advantage of cursor keys, the rest of us had to retype the whole line for every edit.  Current expectations of children's capabilities are absurdly low.

> Would you be open to have a toggle button for the code ?
> Not everyone would want to use Blockly for learning JavaScript.

Our observation has been that children often spend years playing with Scratch.  It becomes a dead-end with no exit path.  Blockly Games was built in reaction to this closed sandbox.  We want them to get familiar with the basic concepts, then be ready to graduate to a real language.

The choice of JavaScript is arbitrary.  At the level we are dealing with here, JavaScript, C, Java, Perl, PHP, Scala, R, Go, and Dart all look virtually identical.
