### ISSUE TITLE
Bird level 5 - A persistent notice blocks actions

### ISSUE THREAD

**Issue by metasean** [google/blockly-games#14]
On https://blockly-games.appspot.com/bird?lang=en&level=5 a notice pops up that tells players to "Click the icon to modify the 'if' block." but it covers the mechanism to modify the 'if' block and doesn't disappear.  

![notice](https://cloud.githubusercontent.com/assets/7552754/6657188/e8224c76-cb08-11e4-8bc7-fedf5ec5f3db.jpg)

It can be worked around by click-n-dragging the elseif control away from the persistent notice block. But the persistent notice itself remains and can not be moved, so it is still blocking the actions area until the elseif control in actually used.

**Comment by NeilFraser** [comment]
Fixed.  Sorry about that.  Blockly's private members changed, and Blockly Games was violating public/private boundaries.
