### ISSUE TITLE
WorkspaceSvg's audio functions not included

### ISSUE THREAD

**Issue by arjenpdevries** [google/blockly-games#15]
I managed to install and build the English version of everything, on a linux FC21 installation.

I tried running the turtle game, both from the filesystem using a file:///home/arjen/src/blocky-games/appengine URL, and using a simple HTTP server started in the appengine directory (using python -m SimpleHTTPServer) and opening http://localhost:8000/turtle.html?lang=en

In both cases, I get errors related to audio;
whether it is Blockly.loadAudio_ or Blockly.playAudio:
  Uncaught TypeError: Blockly.loadAudio_ is not a function
Uncommenting these makes the game run.

I found an ugly fix to resolve the problem: 
  Replace Blockly.loadAudio_ by Blockly.getMainWorkspace().loadAudio_ 
(And, doing the same for playAudio of course).

I guess there may be a more elegant resolution that applies to all instances of the games at once?

Cheers, and btw, I really like blockly, got students started on code.org, and now believe that the blockly-games are excellent next steps for the pupils I am working with to make further progress.

So thanks!

Arjen

PS:
I posted the issue here: https://groups.google.com/forum/#!topic/blockly-games/F2D3RPZUax0
Is the group forum the place to report issues, or is this route straight to github preferred?

PS:
I would be helped with a streamlined instruction on how to create a pull request for a given solution for a report like this...

**Comment by NeilFraser** [comment]
The Blockly Games codebase has been updated to be compatible with the current Blockly codebase.  This error is now resolved.

**Comment by arjenpdevries** [comment]
Great thank you Neil!
