### ISSUE TITLE
Black blocks in compiled mode

### ISSUE THREAD

**Issue by davidkmrcode** [google/blockly-games#168]
I'm trying to incorporate Blockly Games on my website, with a few code changes. I copied the built site into my code base, and then checked out the original source and ran make deps, and then ran make puzzle-en, and copied over the resulting compressed.js to my website. Everything was fine, except none of the blocks had color anymore (see attached).
![puzzle](https://user-images.githubusercontent.com/25348488/71326570-89ec5680-24b1-11ea-9e7a-caca997a9eeb.png)

When I tried running make maze-en, the resulting code also produced blocks with no color, the text "turnLeftturnRight" at the bottom left, and functionality for moving the guy through the maze broke.

Am I building the code wrong, and copying over the resulting compressed.js incorrectly?

**Comment by NeilFraser** [comment]
Upstream issue with Blockly.  They break colours in compiled mode every six months or so: https://github.com/google/blockly/issues/3397

I'm going to change the build to pull from their master branch rather than develop.

**Comment by NeilFraser** [comment]
Makefile changed.  Pull, make clean, make deps, make en.  Should be working again.  I'll leave this bug open until Blockly fixes the issue on the develop branch.
