### ISSUE TITLE
The requested URL Error

### ISSUE THREAD

**Issue by skhendake** [google/blockly-games#17]
Error: Not Found

Error: Not Found
The requested URL /maze?lang=en was not found on this server.

![workspace 1_124](https://cloud.githubusercontent.com/assets/4899603/8206602/addf9bae-1518-11e5-8e20-ffdbd44c4a84.png)

**Comment by arjenpdevries** [comment]
I do not know how deploying works on appspot, but I think the address should be maze.html and not maze

(You probably first need to start a webserver to serve the content though.)

**Comment by megyltv** [comment]
I think maybe the problem is not the part of the URL /maze?lang=en because I did not have that error. But I realized that when I was redirected to the maze it was with this URL: https://blockly-games.appspot.com/maze?lang=en    

(the left part is different)
