### ISSUE TITLE
Using ES8 features with blockly build

### ISSUE THREAD

**Issue by davidkmrcode** [google/blockly-games#172]
I tried to use async/await with the blockly build, but got the following when trying to make en:

[JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT8 mode or better: async function.

Is there a way to use ECMASCRIPT8 features with the build?

**Comment by NeilFraser** [comment]
You will need to change the 'language_in' property here:
https://github.com/google/blockly-games/blob/master/build-app.py#L224

Here's a list of options supported by the Closure Compiler:
https://github.com/google/closure-compiler/wiki/Flags-and-Options
