### ISSUE TITLE
Escaped query string parameter causing skin to not register

### ISSUE THREAD

**Issue by davidkmrcode** [google/blockly-games#175]
For maze, when I click on the level bubble links, I'm taken to a URL like the following:

https://blockly.games/maze?lang=en&level=2&amp;skin=0

The &amp; before "skin" should simply be &, and this is causing the skin to not register (in the case of skin=1 and skin=2).

**Comment by NeilFraser** [comment]
Confirmed.  @moniika This looks like yours.

Steps to recreate:
Go to https://blockly.games/maze
Switch to astronaut skin.
Click on '10'.

Expected: Level 10, astronaut.
https://blockly.games/maze?lang=en&level=10&skin=1

Actual: Level 10, pegman.
https://blockly.games/maze?lang=en&level=10&amp;skin=1

**Comment by NeilFraser** [comment]
Fixed.  Will rebuild overnight and if all goes well push to prod by noon tomorrow (California time).
Thanks for the report, @davidkmrcode
