### ISSUE TITLE
All content not loading

### ISSUE THREAD

**Issue by tteggelit** [google/blockly-games#18]
I cloned the repo and followed the installation procedure. I have an apache server running on CentOS 7. When I go to /blockly/games/appengine/index.html I get the GUI to select the app. If I select an app from there (say Maze) I just get the directory contents of of /blockly/games/appengine/maze/. If I go to /blockly/games/appengine/maze.html, the app partially loads, but not the actual progress window:

https://www.dropbox.com/s/tyxith0poiwzhsr/Screenshot%202015-06-23%2008.34.17.png?dl=0

I don't get any errors on the console or in the web logs (other than missing /common/storage.js). This feels like a web server configuration I'm missing. Any help? I'm trying to get this configured for a programming class that starts Monday where I won't have external network so I need to get it working self-contained. Thanks!

**Comment by NeilFraser** [comment]
Does the offline download package work for you?
https://github.com/google/blockly-games/wiki/Offline

**Comment by tteggelit** [comment]
The offline version does indeed work! Thanks. What's the difference between the offline and the source compiled version?

**Comment by NeilFraser** [comment]
The master branch of Blockly Games (old) is not compatible with the master branch of Blockly (new) at the moment.  This should be resolved soon.

**Comment by nikmanG** [comment]
I am actually getting a similar problem with the JavaScript not working properly and not showing/reacting fully. The offline version works okay but the build fails.

**Comment by deherinu** [comment]
I want to do some changes on Maze, Also tried to use the build version but I have the same problem, also I did some changes on the maze.js with window.alert (make command was ok but the alert didnt works). I need to change the maze exercise and get the number of tries. Can I do that with the Offline version? Thank you, nice work

**Comment by deherinu** [comment]
Its works! I used this pull
https://github.com/google/blockly-games/pull/16

The solution: 
https://github.com/arjenpdevries/blockly-games/commit/0c9d6f954db2c1f9d803c43dd2d6be0bc107a8c5

Now I can build my changes
