### ISSUE TITLE
Translations not showing up at blockly-games.appspot.com

### ISSUE THREAD

**Issue by siebrand** [google/blockly-games#19]
In https://translatewiki.net/wiki/Thread:Support/Translation_not_showing_up_in_Blockly_Games a translator is asking why his translations in Hungarian as not showing up at blockly-games.appspot.com.

I'm assuming this has to do with two things:
* How often JSON based translations are converted to JavaScript.
* How often the code is deployed on the the site.

Can some insight please be provided into what has to happen, and how often this happens, before translations reach the live site?

**Comment by lajthabalazs** [comment]
Would be great to be able to use the translations. How could I help?

**Comment by lxlalexlxl** [comment]
We have same problem with Ukrainian translation. The https://github.com/google/blockly-games/blob/master/json/uk.json file was changed 2 month ago, but we do not see updates in https://blockly-games.appspot.com/ . How to solve this problem?

**Comment by nasko** [comment]
Same for Bulgarian - `bg.json` has been modified 4 months ago, bug there's no Bulgarian translation on the live site.

**Comment by NeilFraser** [comment]
After nearly a year-long gap, a new version has just been pushed live.  Future updates should be more regular as we get a dedicated engineer on Blockly Games.
