### ISSUE TITLE
How to add multiple Finish/Checkpoints

### ISSUE THREAD

**Issue by mriganksingh** [google/blockly-games#193]
How to add multiple Finish/Checkpoints in place of just a single Finish point in Maze Game?

**Comment by NeilFraser** [comment]
Interesting question, not one that's been asked before.  Maze doesn't support this, but it could be added.  You'd need to change `Maze.finish_` from an X/Y object, to an array of X/Y objects.  You'd also need to create multiple `finishMarker` objects and keep them in an array.
