### ISSUE TITLE
blockly.games dns problem?

### ISSUE THREAD

**Issue by perfack** [google/blockly-games#198]
I cannot access blockly.games. IP address cannot be found.
Address blockly-games.appspot.com redirects to blockly.games. 
Any suggestions?

**Comment by NeilFraser** [comment]
The DNS on Blockly Games is broken due to a domain name transfer.  Make take a couple of hours for the fix to propagate.  Should be a one-time thing.  Sorry about that, and thanks for letting us know.

**Comment by NeilFraser** [comment]
Fixed!
