### ISSUE TITLE
unable to access closure-compiler.jar file on Ubuntu

### ISSUE THREAD

**Issue by Prashantg22** [google/blockly-games#200]
when I try to run the make deps command on commandline, it stops executing with an error Unable to access jar file third-party-downloads/closure-compiler.jar

**Comment by Seransei** [comment]
Hi,

I ran across this same error which led me to directly download closure-compiler from https://github.com/google/closure-compiler/wiki/Binary-Downloads.

I found that the link to compiler-latest.zip isn't up anymore (apparently).

Downloading myself the latest version makes the "make deps" command works properly but I run across another problem with closurebuilder.py.

**Comment by Seransei** [comment]
Hi again, 

#203 I found a way to fix it and proposed it, for now you can try this but you will find another problem I described in #201

**Comment by NeilFraser** [comment]
The pre-built closure-compiler.jar is no longer being published.  Here's the bug where they acknowledge that this is intentional and permanent: https://github.com/google/closure-compiler/issues/3662#issuecomment-675524506

**Comment by NeilFraser** [comment]
Fortunately the latest version is available from unpkg.com
Fixed via https://github.com/google/blockly-games/commit/cb9988e9ae696551d0490bc255d0293c817814a2

Thanks for the report.
