### ISSUE TITLE
No bottom dent inside blocks

### ISSUE THREAD

**Issue by ByteEater-pl** [google/blockly-games#215]
Instructions which have room for other instructions inside them have a peg on the top of the space to match the dent of the first inserted block. However, there's no dent at the bottom, so the peg in the bottommost inserted block is mismatched, visually disconcerting and potentially causing the user to question if he's doing it correctly.

**Comment by ByteEater-pl** [comment]
Actually this is about Blockly itself (whose repo is harder to find), so please move the issue if possible and appropriate.

**Comment by NeilFraser** [comment]
This is a common and a valid request.  However, implementing it solves one small problem and immediately creates a second, much bigger problem.  We even have documentation on this issue:

Nesting sub-stacks
https://developers.google.com/blockly/guides/app-integration/best-practices#2_nesting_sub-stacks
