### ISSUE TITLE
No confirmation or feedback of correct solution in Movie section

### ISSUE THREAD

**Issue by JamesNewton** [google/blockly-games#220]
When building the objects in the Movie section, there is no way to test or complete each level.

**Comment by NeilFraser** [comment]
Playing the movie tests completeness.

![Screen Shot 2021-05-31 at 23 22 12](https://user-images.githubusercontent.com/250480/120276178-374ac880-c267-11eb-81a8-7813d907729f.png)

**Comment by JamesNewton** [comment]
There is no play bar on the first game:
![image](https://user-images.githubusercontent.com/419392/120360300-71df5000-c2bd-11eb-858c-189e489101e3.png)

**Comment by cpcallen** [comment]
The very first level requires no animation, so it will automatically show successful completion as soon as you construct the figure shown (correct shapes in the correct colours in the correct locations).
