### ISSUE TITLE
Ghosted image makes color impossible to decern

### ISSUE THREAD

**Issue by JamesNewton** [google/blockly-games#221]
e.g. on the first challenge in the Movie Level, the "body" of the figure is apparently blue? But it's very difficult to see that. Not to mention impossible for people with color blindness. 

I would suggest making the color matching optional, or using another method to show what the result is supposed to be, like a texture or fill pattern.

**Comment by NeilFraser** [comment]
> I would suggest making the color matching optional

Colour matching is optional.  There are no colour requirements at all.

![Screen Shot 2021-05-31 at 23 19 14](https://user-images.githubusercontent.com/250480/120275769-a83db080-c266-11eb-82aa-0d6eadacd480.png)

**Comment by JamesNewton** [comment]
I completely fail to see how you got a test for completeness to run on the first game... there is no play bar, and using exactly the same blocks, nothing happens when I duplicate the image. 

Also, the presence of color blocks /implies/ that color must be matched. If it doesn't care, so be it, but then the ghosted image really shouldn't have color in the first place.

**Comment by JamesNewton** [comment]
Ah. I found it. The ghosted image has arms made from lines. The width of the ghosted arm line is not given as a number, but instead is matched by the player increasing the arm line width until the ghosted image is matched. This happens with a line width of FOUR. Try it and see that the line completely covers the ghosted arm line. You are putting in 5, probably because you know what the expected width is from the source code. Your 5 /also/ covers the ghosted arm, but a player slowly increasing the size to 4 would not know, as I did not know, to keep increasing the width to 5, which then triggers the finish.

**Comment by cpcallen** [comment]
I think that expecting the student to do a certain amount of trial and error is absolutely fine here, but I agree that it is pretty hard to tell just by looking at it that lines of width 4 are too narrow.

Of course, I guessed 5 to start just because all the other measurements are multiples of 5.
