### ISSUE TITLE
build/closurebuilder.py: No such file or directory

### ISSUE THREAD

**Issue by promo360** [google/blockly-games#224]
Hello!

`make deps` started returning the error `build/closurebuilder.py: No such file or directory`.

Perhaps this is due to a recent change [Delete open-sourced Python helper scripts](https://github.com/google/closure-library/commit/749634639af6b04bfe1d9d890bb037811e390b61#diff-d81c940b6fdad2a128c0bc02d24814121b1c6a9373537d7227d4f22821f7ba36) в closure-library.

**Comment by nnyy0130** [comment]
[closurebuilder.py.zip](https://github.com/google/blockly-games/files/6944568/closurebuilder.py.zip)
copy this file to build/ document

**Comment by NeilFraser** [comment]
This was fixed in https://github.com/google/blockly-games/commit/dea68a7ff38be92d83514dbbf4560030f919c919
