### ISSUE TITLE
Can't see the YES and CANCLE button after building

### ISSUE THREAD

**Issue by LittleNewton** [google/blockly-games#226]
I build this interesting web game on RedHat 8.4 x86-64 OS.

I do really build it successfully and it can run well. But there is only on small problem that I can't see the YES and CANCLE buttons like the following picture shows.

![image](https://user-images.githubusercontent.com/17793356/134241168-02b854ca-ae18-464b-86a9-2fec517ce624.png)

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
