### ISSUE TITLE
Level 3 of Maze might need `dialogHelpCapacity`

### ISSUE THREAD

**Issue by acbart** [google/blockly-games#23]
I believe that level 3 of the maze might need a certain dialog. It's referenced in 
https://github.com/google/blockly-games/blob/master/appengine/maze/js/maze.js#L660

And present in level 4: 
https://github.com/google/blockly-games/blob/master/appengine/maze/template.soy#L164

But not in level 3:
https://github.com/google/blockly-games/blob/master/appengine/maze/template.soy#L153

Adding it into my local fork fixes a "Uncaught TypeError: Cannot read property 'nodeType' of undefined" error. I'm getting another one, but I'm not sure how that's being caused since there is a `dialogHelpRepeat`

**Comment by NeilFraser** [comment]
Fixed.  Thanks.
Should appear in tomorrows release.
