### ISSUE TITLE
Requirements for build should specify python version.

### ISSUE THREAD

**Issue by jdalbey** [google/blockly-games#234]
I think it would be helpful if [this page](https://github.com/google/blockly-games/wiki/Build) specified that python3 is required.

I followed the directions given and `make games` failed until I thought to edit the `Makefile` and change '`python`' to '`python3`'.

**Comment by NeilFraser** [comment]
Good point.  I've edited the build scripts to throw an exception if python 2 is being run:
https://github.com/google/blockly-games/commit/9d43d1aefba970e94a29c4344d1d4b03ec676b85
