### ISSUE TITLE
Turtle level 3 message says "There's a new block..." twice.

### ISSUE THREAD

**Issue by earth-elephant** [google/blockly-games#236]
In Turtle level 3, the modal shows the message twice:
![blockly-message-bug](https://user-images.githubusercontent.com/118197021/201696077-e1e347af-9257-4d31-ae96-578bb7975027.png)

**Comment by NeilFraser** [comment]
Thank you!  Fixed.

<img width="814" alt="Screen Shot 2022-11-14 at 16 42 08" src="https://user-images.githubusercontent.com/250480/201702534-54ad7177-5162-4fb5-bafb-099876b0d118.png">

**Comment by NeilFraser** [comment]
By the way, excellent bug report.  Clear and helpful.  Welcome to GitHub, @earth-elephant!
