### ISSUE TITLE
How to modify the pic of the pond-tutor game's avatar

### ISSUE THREAD

**Issue by Pvtwen** [google/blockly-games#239]
Here is the question, How to change the duck to another pic like human or something?
![K}D1`()LO6O@FMK{G5PE7HU](https://user-images.githubusercontent.com/60743612/229278017-73c6bcc8-217e-423a-94c5-4fb0e078fe3e.png)

**Comment by NeilFraser** [comment]
Here's the sprites file:
https://github.com/google/blockly-games/blob/master/appengine/pond/sprites.png

**Comment by Pvtwen** [comment]
> Here's the sprites file: https://github.com/google/blockly-games/blob/master/appengine/pond/sprites.png

got it! thank u.
