### ISSUE TITLE
There was an issue with visualization

### ISSUE THREAD

**Issue by yhbest** [google/blockly-games#24]
![2016-01-22 8 59 59](https://cloud.githubusercontent.com/assets/12862334/12510177/51a0ca36-c14b-11e5-9890-bcefc2f50f37.png)
We build blackly-games through wiki's guide.
However, when we opened "maze.html",
**visualization** didn't work(look at screenshot), script was missing.
and the "Run Program" button didn't work either.

I build it on El Capitan and I used Safari browser.

Thanks for helping :)

**Comment by NeilFraser** [comment]
I believe that this was fixed in the February update.  Prior to that the build was quite broken.
