### ISSUE TITLE
Bug: Arabic Support

### ISSUE THREAD

**Issue by iibrahemali** [google/blockly-games#249]
Hey!
I have tested Maze section of the game, in the Arabic mode, and the translation is kinda literal. As this game specified for kids, I'd recommend to provide an accurate Arabic version of the game.

**Comment by NeilFraser** [comment]
The translations of Blockly and Blockly Games are handled by Translatewiki.  Here are the instructions for contributing translations.  We are always delighted to receive better translations:
https://developers.google.com/blockly/guides/contribute/core/translating
