### ISSUE TITLE
Pond Tutor: Level 8 Goal

### ISSUE THREAD

**Issue by TechplexEngineer** [google/blockly-games#29]
Is the goal of Level 8 on the Pond Tutor for the user to discover that there is a second parameter to the swim function which controls the speed of the swimming?

I guess what I'm really trying to ask is should the target be moving back and forth?
https://blockly-games.appspot.com/pond-tutor?lang=en&level=8

**Comment by NeilFraser** [comment]
Discovering the speed parameter in the documentation is one solution.  But a simpler solution is to just aim: swim(275);
