### ISSUE TITLE
ERRO  Blockly Games : Maze  level 9

### ISSUE THREAD

**Issue by mariaangela** [google/blockly-games#35]
As funções cumprem com os objetivos. Porem o programa não passa de nível.
O link do código:   

https://blockly-games.appspot.com/maze?lang=en&level=9&skin=0#auh7z7

**Comment by NeilFraser** [comment]
That's the correct behaviour.  The loop only checks for completion when it exits it reaches the end of an iteration.  A long time ago we used to break the loop the instant that the user reached the goal (as you expected), but we got feedback from teachers (mostly in Germany) that a stricter execution model was required.

Here is a simpler solution to level 9 that works better:
https://blockly-games.appspot.com/maze?level=9#ssresr
