### ISSUE TITLE
blockly turtle game

### ISSUE THREAD

**Issue by RimishRobolab** [google/blockly-games#37]
Hello Sir,
I want to embed blockly turtle game level 10 to my website.
I want to embed only level 10.
How to do it. what are the different files should i edit

**Comment by NeilFraser** [comment]
Blockly Games is a very large and complicated application, extracting a single level cleanly is not easy.  But if you don't need a minimal installation then all you need to do is edit appengine/turtle/template.soy to remove the level selector, then rebuild everything, and link directly to turtle?level=10 from your website.
