### ISSUE TITLE
cannot access ‘build/closurebuilder.py’: No such file or directory

### ISSUE THREAD

**Issue by yonghuming** [google/blockly-games#44]
i worked on ubunt 14.04 lts,but i got this error :
`--2016-10-14 23:44:08--  https://dl.google.com/closure-compiler/compiler-latest.zip
Resolving dl.google.com (dl.google.com)... 203.208.43.72, 203.208.43.68, 203.208.43.64, ...
Connecting to dl.google.com (dl.google.com)|203.208.43.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5874438 (5.6M) [application/zip]
Server file no newer than local file ‘compiler-latest.zip’ -- not retrieving.

Archive:  compiler-latest.zip
  inflating: closure-compiler-v20160911.jar  
chmod: cannot access ‘build/closurebuilder.py’: No such file or directory
make: **\* [deps] Error 1
`

**Comment by tapaheh** [comment]
Same issue here while building dependencies.

**Comment by tapaheh** [comment]
After installing subversion and running `make deps` the issue goes away

**Comment by NeilFraser** [comment]
We use Subversion for the read-only dependencies rather than Git since Subversion only pulls down the code, whereas Git pulls down the entire repo's history.  Thus Subversion saves a lot of disk space for developers.
