### ISSUE TITLE
can blockly-games be deploy on non GAE  or appot?

### ISSUE THREAD

**Issue by yonghuming** [google/blockly-games#45]
just build on ubuntu 14.04

**Comment by NeilFraser** [comment]
Absolutely.  Blockly Games has almost no server-side components.  This means you don't even need a server.  Just run the build script, and point a browser at 'appengine/index.html'.  It's all static.

That said, there are two things you lose by not being on App Engine.  The Reddit integration of Turtle and Movie, and the link buttons to save levels.  Both of these features are designed to fall off cleanly if Blockly Games is being run statically.

Note that you don't even need to build.  You can just download an offline version here:
https://github.com/google/blockly-games/wiki/Offline
Unzip in and use locally, or upload to any server of your choice.
