### ISSUE TITLE
Custom function in Pond Basic level 8 not displaying correctly

### ISSUE THREAD

**Issue by Aus-Fitzy** [google/blockly-games#5]
I can drag the custom function to the workspace.
When i open the function menu again, the sub menu is all garbled.

![pond8func](https://cloud.githubusercontent.com/assets/5729895/5356795/947b053a-7ff0-11e4-9bba-5f35705a154e.png)
![pond8funcbad](https://cloud.githubusercontent.com/assets/5729895/5356796/949db4b8-7ff0-11e4-9a5a-41d6575bff66.png)

I tried on the [blockly](https://developers.google.com/blockly/) site and it seemed to work as expected.

![blockyfunc](https://cloud.githubusercontent.com/assets/5729895/5356794/942087c2-7ff0-11e4-898f-e8bee1a0bfdc.png)

I tried in Opera, Chrome and IE.

Filling up the function so that there is no empty 'slots' doesn't make any difference

The dev tools in chrome report
Uncaught TypeError: Cannot read property 'P' of null @ compressed.js:formatted:9676
I think this is in the blockly code, not blockly-games,however since it works on  the blockly site, i would think something is broken before it reaches that code.

My guess is that something in /appengine/pond/js/blocks.js around lines 668 to 720 is not set up correctly.

**Comment by emorrp1** [comment]
Agreed this was really annoying since those levels started getting crazy complicated.  The issue is missing `WITH` fields when creating the caller blocks:

    this.getField_('WITH').setVisible(!!this.arguments_.length);
    Uncaught TypeError: Cannot read property 'setVisible' of null -- procedures.js:539
    Blockly.Blocks.procedures_callnoreturn.setProcedureParameters

 The fix is to add the below line after lines 733 and 768 of `/appengine/pond/js/blocks.js`. This allows the creation of "callnoreturn"/"callreturn" blocks, though the input value names oddly disappear when the mutator window is opened.

          .appendField('', 'WITH');

Patch:

    diff --git a/appengine/pond/js/blocks.js b/appengine/pond/js/blocks.js
    index 5c76907..b4aa14d 100644
    --- a/appengine/pond/js/blocks.js
    +++ b/appengine/pond/js/blocks.js
    @@ -730,7 +730,8 @@ Blockly.Blocks['procedures_callnoreturn'].init = function() {
       this.setColour(290);
       this.appendDummyInput()
           .appendField('', 'NAME')
    -      .appendField('(');
    +      .appendField('(')
    +      .appendField('', 'WITH');
       this.appendDummyInput('TAIL')
           .appendField(');');
       this.setInputsInline(true);
    @@ -765,7 +766,8 @@ Blockly.Blocks['procedures_callreturn'].init = function() {
       this.setColour(290);
       this.appendDummyInput()
           .appendField('', 'NAME')
    -      .appendField('(');
    +      .appendField('(')
    +      .appendField('', 'WITH');
       this.appendDummyInput('TAIL')
           .appendField(')');
       this.setInputsInline(true);

**Comment by NeilFraser** [comment]
Fixed from the Blockly side of things ('WITH' is now optional).  Will rebuild overnight and push a new version tomorrow.  Thanks!
