### ISSUE TITLE
ERROR - this language feature is only supported for ECMASCRIPT6 mode or better

### ISSUE THREAD

**Issue by prakashg** [google/blockly-games#52]
With "make maze-en", I get the following error:

rcs appengine/template.soy
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/maze/generated/en/soy.js --srcs appengine/maze/template.soy
python build-app.py maze en

Maze - en - uncompressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2247 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..

Maze - en - compressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2247 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..
third-party/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
is prefererred over using this script for performing JavaScript compilation.

Please migrate your codebase.

See:
https://github.com/google/closure-compiler/wiki/Managing-Dependencies

third-party/build/closurebuilder.py: Compiling with the following command: java -client -jar third-party/closure-compiler.jar --flagfile /tmp/tmpC6qhbJ
appengine/third-party/blockly/core/blockly.js:391: WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
 * @return {function} A function that calls jsonInit with the correct value
                    ^

appengine/third-party/blockly/core/field.js:71: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
 * @type {string=}
                ^

appengine/third-party/blockly/core/variables.js:236: WARNING - Bad type annotation. missing closing ) See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
 * @param {function(null|undefined|string)=} opt_callback A callback. It will
                        ^

appengine/third-party/blockly/core/workspace_svg.js:1011: ERROR - this language feature is only supported for ECMASCRIPT6 mode or better: const declaration. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT or higher to enable ES6 features.
  const PIXELS_PER_ZOOM_STEP = 50;
  ^

1 error(s), 3 warning(s)
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 293, in <module>
    main()
  File "third-party/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/home/ubuntu/workspace/blockly-games/third-party/build/jscompiler.py", line 160, in Compile
    raise JsCompilerError('JavaScript compilation failed.')
jscompiler.JsCompilerError: JavaScript compilation failed.

**Comment by NeilFraser** [comment]
Arg, someone submitted a 'const' declaration instead of 'var'.  I've fixed this in the develop branch of Blockly, but it will take a little while to propagate over to the master branch.  In the mean time, manually edit appengine/third-party/blockly/core/workspace_svg.js and change the offending const to var.

Sorry about that, and thanks for reporting it.

I'll also file a bug over at Blockly regarding the three type warnings.

**Comment by prakashg** [comment]
Thanks for the extremely fast debugging & fix!
