### ISSUE TITLE
Blcokly build error | BlocklyStorage is undeclared

### ISSUE THREAD

**Issue by vivekarora2014** [google/blockly-games#57]
Hello,

I am facing issues while 'make' the pond-duck-en. I successfully executed 'make deps' but while building pond-duck-en

`appengine/js/lib-dialogs.js:374: ERROR - variable prettyPrintOne is undeclared
    if (typeof prettyPrintOne == 'function') {
               ^^^^^^^^^^^^^^

appengine/js/lib-interface.js:49: ERROR - variable BlocklyStorage is undeclared
    BlocklyStorage['HTTPREQUEST_ERROR'] =
    ^^^^^^^^^^^^^^
`

I cloned the project from https://github.com/google/blockly-games.git and did not change any file. Is this a known issue because I did not find anything concrete to fix this. Kindly help. Thanks in advance. I am using Ubuntu.

**Comment by NeilFraser** [comment]
Duplicate: Issue #56
