### ISSUE TITLE
Nothing append after compilation

### ISSUE THREAD

**Issue by cygu973973** [google/blockly-games#59]
Hello,
I built a blockly-games turtle-en from sources and this forum helps but when I try to launch turtle.html and a blank page appears .... I noticed that generated files (compressed en uncompressed in turtle/generated/en/)  have been created by building. Any help ?

**Comment by NeilFraser** [comment]
Several dependencies (including Blockly) changed over time, breaking the build.  Blockly Games has been updated so that everything builds properly now.
