### ISSUE TITLE
nothing to show in games except maze and puzzle 

### ISSUE THREAD

**Issue by saranshcurieo** [google/blockly-games#60]
This is the error it shows in the console. Maze and Puzzle are working fine but the rest are not.
`GET file:///common/storage.js net::ERR_FILE_NOT_FOUND
compressed.js:190 Uncaught Error: Error when registering mutator "controls_if_mutator": missing required property "domToMutation"
    at zi (compressed.js:190)
    at yi (compressed.js:188)
    at compressed.js:559`

**Comment by NeilFraser** [comment]
Several dependencies (including Blockly) changed over time, breaking the build.  Blockly Games has been updated so that everything builds properly now.
