### ISSUE TITLE
make en fails

### ISSUE THREAD

**Issue by annasindarsin** [google/blockly-games#63]
I am new to blockly. I have followed the steps for building blockly games from this site: http://www.catch.jp/wiki/index.php?Build_Blockly-Games_Win
when I tried the 'make en' command on cygwin, I got following error:

java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/generated/en/soy.js --srcs appengine/template.soy
Error: Unable to access jarfile third-party/SoyToJsSrcCompiler.jar
make: *** [Makefile:65: common-en] Error 1

Does anyone know how to solve it? It will be a huge help.

**Comment by harisnp** [comment]
I think you can try the following. 

https://github.com/harisnp/mazegameworkingcybersquare.git

**Comment by petrusek** [comment]
You have probably forgot to run `make deps` which downloads the dependencies.

**Comment by annasindarsin** [comment]
Thank you for your responses :) I used my coworker's old files which had succeeded to make en and it worked for me too.

**Comment by nantapat** [comment]
@annasindarsin  do you mind if I want to request this file from you? because I met the problem that you had met before.

**Comment by annasindarsin** [comment]
@nantapat sorry, it was company-restricted so I can't share it. you may try the link from @harisnp :) hope this helps.

**Comment by rachelbriggs** [comment]
Having the same problem.  Ran 'make deps' first and it fails when running 'make en'.
