### ISSUE TITLE
Building errors (linux mint)

### ISSUE THREAD

**Issue by JerryFox** [google/blockly-games#69]
make deps

ends with error: 
Archive:  compiler-latest.zip
  inflating: closure-compiler-v20171112.jar  
chmod: cannot access ‘build/closurebuilder.py’: No such file or directory
make: *** [deps] Error 1

make en

ends with error: 
Index - en - uncompressed:
Traceback (most recent call last):
  File "build-app.py", line 224, in <module>
    main(sys.argv[1], sys.argv[2])
  File "build-app.py", line 93, in main
    write_uncompressed(name, lang)
  File "build-app.py", line 110, in write_uncompressed
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [index-en] Error 1

Any idea? 

Thanks! 

J.V.

**Comment by NeilFraser** [comment]
I just did a `make clean` and had no problems with `make deps`.  What OS are you using?

List the directory of `third-party/build/`  It should contain:
```
closurebuilder.py	depstree_test.py	jscompiler.py		source.py		treescan.py
depstree.py		depswriter.py		jscompiler.pyc		source.pyc		treescan.pyc
depstree.pyc		depswriter_test.py	jscompiler_test.py	source_test.py
```

**Comment by CelineDknp** [comment]
I'm on Ubuntu and having the same problem. The ``build/`` directory doesn't even get created...

(Hope I'm not digging to old a post)

**Comment by CelineDknp** [comment]
So, one of the problem was that I didn't have Subversion and it would not signal it (the command you suggested did, and I installed it). Then it failed because of those lines : 
```
# There are bad dependencies in debug_loader_integration_tests.
# We don't use it anyway.  Kill it.  27 April 2018
rm -r $(APP_ENGINE_THIRD_PARTY)/goog/debug_loader_integration_tests/
```
It could not find the files to delete (they weren't there, I checked), so I simply commented it out and it successfully finished.

Now, when I run `sudo make turtle-en` (apparently it should run with sudo or it can't access some files); I get : 
```
Turtle - en - compressed:
appengine/third-party/blockly/gulpfile.js:61: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: template literal.

appengine/third-party/blockly/tests/test_runner.js:33: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: arrow function.
```
And I'm stuck again (I get the same error for other games).

**Comment by NeilFraser** [comment]
Thanks.  Always fun when our dependencies change and break us.

With respect to the debug_loader_integration_tests, yes, simply commenting them out was the correct action.  The Closure team have fixed this issue as a result of my report to them.  I've deleted the offending 'rm' from the makefile.  https://github.com/google/blockly-games/commit/9053f7122ae0b2891198ab0e9d0bc324ba306c0b

With respect to the ES6 errors, I've reported the issue to Blockly and submitted a PR to them.  https://github.com/google/blockly/pull/1857  In the mean time, you can simply delete those two files:
```
appengine/third-party/blockly/gulpfile.js
appengine/third-party/blockly/tests/test_runner.js
```

**Comment by CelineDknp** [comment]
That works !

Thanks for the great, friendly and quick support !
