### ISSUE TITLE
Touch events aren't recognized

### ISSUE THREAD

**Issue by andreibosco** [google/blockly-games#7]
I've tested blockly on:
- Android tablet (Android 4.2.2)
- Chrome (39.0.2171.95 - using developer tools with touch emulation)
- Firefox (34.0.5 - using developer tools with touch emulation)

In none of them touch events were recognized. I'm able to click/touch blocks, but I can't drag them.

**Comment by NeilFraser** [comment]
I think updates to the Blockly core library have fixed this.

**Comment by andreibosco** [comment]
Thank you, I will check it out.
