### ISSUE TITLE
Unable to change numbers in Blockly games

### ISSUE THREAD

**Issue by Keagan-Malan** [google/blockly-games#76]
Good day

I am currently using Blockly on a tablet, and I find that we are unable to change the numbers in some of the blocks. 
So we find it impossible to accomplish the games.

Also Pond is impossible to play, as we are unable to make the duck move due to this issue. 

Please can someone assist. 

Thanking you kindly 
Keagan Malan

**Comment by NeilFraser** [comment]
Which tablet, Android or iOS?

**Comment by Keagan-Malan** [comment]
Android

**Comment by NeilFraser** [comment]
I'm able to edit the number fields in blocks on my Android phone.  Will keep checking other devices...

**Comment by Keagan-Malan** [comment]
Hi Neil 

We have tried on a Samsung tablet as well as a Lenovo tablet, and we are unable to edit the number fields on both. We were able to edit on the samsung phones we tested on, but no luck with the tablets.

**Comment by NeilFraser** [comment]
Can you try two things for me.  First, try the new (unreleased) version of Blockly Games:
https://beta-dot-blockly-games.appspot.com/
(Feel free to use this, the only bug we are tracking is layout issues in Arabic and Hebrew).
If this version works, then the problem has been fixed and we can close this issue.

Second, if the above version does not work, try this:
https://blockly-demo.appspot.com/static/demos/code/index.html
If this version does not work, then it's an upstream Blockly issue and we can get the Blockly team to fix it.

Thanks!

**Comment by Keagan-Malan** [comment]
Hi Neil.

We are currently testing these solutions to see if we come right on our tablets.

**Comment by JasonTame** [comment]
Good day Neil,

I work with Keagan and have been troubleshooting this issue. The problem was on our side - we are running Blockly through a WebView on an Android app, and needed to use WebChromeClient with the WebView to get the pop ups to work. 

We've changed the code, and everything is working correctly now. Thanks for your help!

**Comment by NeilFraser** [comment]
No problem!

**Comment by NeilFraser** [comment]
Just so you know, although Blockly uses modal prompt() pop-ups by default, it is built so that they can be easily replaced.  Here's a demo:
https://blockly-demo.appspot.com/static/demos/custom-dialogs/index.html
