### ISSUE TITLE
my language isn't update on my local blockly games

### ISSUE THREAD

**Issue by nantapat** [google/blockly-games#78]
Hi, I'm may. I need some help. I have already translated blockly games to my language and th.json file has been updated. But when I run index.html in my local, some parts of games are still in english language, not thai language. I want to know why blockly games doesn't update my language into website. If you know the solution of this issue, please tell me. Thanks you.
![image](https://user-images.githubusercontent.com/14249884/38653764-6c62ce72-3e36-11e8-80ad-93bfd030449c.png)

**Comment by NeilFraser** [comment]
You can see (and play with) a preview of Thai on our staging server:
https://beta-dot-blockly-games.appspot.com/?lang=th

The next official release is taking longer than usual to get out thanks to changes relating to GDPR.  In the mean time, you are welcome to use our staging server.

**Comment by NeilFraser** [comment]
Full release has just been pushed.
