### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by ChristosPatsalis** [google/blockly-games#81]
Hi,
When I try to build blockly games, when I write the command make deps I always get this error:
java -jar third-party/closure-compiler.jar\
 --js appengine/third-party/JS-Interpreter/acorn.js\
 --js appengine/third-party/JS-Interpreter/interpreter.js\
 --js_output_file appengine/third-party/JS-Interpreter/compiled.js
Error: Unable to access jarfile third-party/closure-compiler.jar
make: *** [Makefile:110: deps] Error 1

What can I do about this?

**Comment by NeilFraser** [comment]
Try the following commands one by one and see if one is failing:

```
cd third-party
wget -N https://dl.google.com/closure-compiler/compiler-latest.zip
unzip -o compiler-latest.zip -x COPYING README.md
mv -f closure-compiler-v*.jar closure-compiler.jar
```

**Comment by ChristosPatsalis** [comment]
Thanks that worked, but it seems I have the same problem with make en command.
$ make en
mkdir -p appengine/generated/en/
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces                                                                                                                 --isUsingIjData --outputPathFormat appengine/index/generated/en/soy.js --srcs a                                                                                                                ppengine/index/template.soy
Error: Unable to access jarfile third-party/SoyToJsSrcCompiler.jar
make: *** [Makefile:21: index-en] Error 1

And I believe I will get the same again in making the games, make puzzle-en for example.

**Comment by NeilFraser** [comment]
Strange that the four lines I provided worked, they are exactly the same lines that should be executed by `make deps`.

Well, let's try it again.  Here are the three lines from the make file that setup the Soy compiler.  Try running them one by one:
```
cd third-party
wget -N https://dl.google.com/closure-templates/closure-templates-for-javascript-latest.zip
unzip -o closure-templates-for-javascript-latest.zip SoyToJsSrcCompiler.jar
```

**Comment by eldos-dl** [comment]
The URL [https://dl.google.com/closure-compiler/compiler-latest.zip](https://dl.google.com/closure-compiler/compiler-latest.zip) is giving 404 error.

**Comment by NeilFraser** [comment]
@eldos-dl The Closure Compiler disappearance was addressed here: https://github.com/google/blockly-games/issues/200
