### ISSUE TITLE
make maze-en error

### ISSUE THREAD

**Issue by hyunji3190** [google/blockly-games#85]
I get this error, and I am not sure what is wrong in build-app.py.
does anyone else have the same problem?
plz help! I want to make new curriculum from this source code.  

Traceback (most recent call last):
  File "build-app.py", line 214, in <module>
    main(sys.argv[1], sys.argv[2])
  File "build-app.py", line 42, in main
    language(name, lang)
  File "build-app.py", line 72, in language
    write_compressed(name, lang)
  File "build-app.py", line 201, in write_compressed
    script = " ".join(script)
TypeError: sequence item 0: expected str instance, bytes found
make: *** [index-en] Error 1

**Comment by NeilFraser** [comment]
Found it.  You are using Python 3 whereas I use Python 2.  I've modified the build script to convert Python 3's byte arrays to strings.  Pull down the latest copy and it should be fixed.  Thanks for reporting this.
