### ISSUE TITLE
Nginx server with appengine

### ISSUE THREAD

**Issue by BradChan** [google/blockly-games#90]
I had built the blockly-games and start the server with nginx. nginx.conf with following:
server {
        listen       5252;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   blockly-games;
            index  index.html;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

While the nginx started, Browse to the http://localhost:5252/ or  http://localhost:5252/index.html is successfully.But browse to the http://localhost:5252/turtle/?lang=en show "Forbidden 403". Browse  to the http://localhost:5252/turtle.html?lang=en is successful. I think that the appengine i built is static project. Therefore the Gallary is not showed. If i need to custom the gallery, how can i do?

**Comment by NeilFraser** [comment]
As you know, the project is designed for App Engine, it's routing table is here:
https://github.com/google/blockly-games/blob/master/appengine/app.yaml
To use Nginx, you'd need to replicate this routing table using Nginx's configuration.  That should be pretty straight forward (just map '/turtle' to '/turtle.html', etc).  You don't want ".html" visible on any URL.

However, the gallery is written specifically for the App Engine's Datastore.  The code is here:
https://github.com/google/blockly-games/tree/master/appengine/gallery_api
It's not very complex, but all those files would need to be rewritten to support whatever storage API you plan to use (e.g. SQL).

If you can use App Engine, do so.  It will save a ton of work on your end.
