### ISSUE TITLE
404 error at compiler download link

### ISSUE THREAD

**Issue by Protosac** [google/blockly-games#91]
https://dl.google.com/closure-compiler/compiler-latest.zip

If you're trying to install using `make deps` today, you'll get a 404.

**Comment by NeilFraser** [comment]
Confirmed.

From this page:
https://developers.google.com/closure/compiler/
The "Download the application" link goes 404.

Filing a bug with Google...

**Comment by NeilFraser** [comment]
For internal Google tracking purposes, this is b/115784701.

**Comment by NeilFraser** [comment]
Fixed on Google's end.
