### ISSUE TITLE
ERROR - This language feature is only supported for ECMASCRIPT6 mode or better

### ISSUE THREAD

**Issue by manfeel** [google/blockly-games#92]
[make_deps_logs.txt](https://github.com/google/blockly-games/files/2399678/make_deps_logs.txt)
[make_en_logs.txt](https://github.com/google/blockly-games/files/2399679/make_en_logs.txt)

the `make deps` procedure complete successfully without any errors, but when `make en`, the error happens:
```
➜  blockly-games git:(master) make en
mkdir -p appengine/generated/en/
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/index/generated/en/soy.js --srcs appengine/index/template.soy
python build-app.py index en

Index - en - uncompressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2440 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..

Index - en - compressed:
appengine/third-party/blockly/accessible/app.component.js:52: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: template literal.

appengine/third-party/blockly/accessible/block-options-modal.component.js:38: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: template literal.

appengine/third-party/blockly/accessible/field-segment.component.js:36: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: template literal.

appengine/third-party/goog/debug/tracer_test.js:77: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: const declaration.

#####################################
##### details in attached files #####
#####################################

appengine/third-party/goog/ui/sliderbase_test.js:92: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: default parameter.

547 error(s), 0 warning(s)
```
PS: The problem encountered under osx(yosemite 10.10.4) and Ubuntu(16.04 LTS) is exactly the same.
Can anybody help me resolve this problem? thanks a lot!

**Comment by NeilFraser** [comment]
Confirmed.  Something changed in the Closure Compiler.  Investigating...

In the mean time, the previous version of Closure Compiler works fine.  After you run `make deps`, download https://dl.google.com/closure-compiler/compiler-20180805.zip extract the jar file, rename it to `closure-compiler.jar`, then replace the one in `blockly-games/third-party`.

**Comment by manfeel** [comment]
Great! Thank @NeilFraser ! , Follow your tips and everything works well again. ;-)

**Comment by NeilFraser** [comment]
I think the solution is in build-app.py on line 179 to change 'language_in' to 'language_out'.  Initial results seem to work, but I want to test this a bit more before committing that change.

**Comment by NeilFraser** [comment]
Committed.  Thanks for the bug report.
