### ISSUE TITLE
Conditional Block is not working in Chrome, Safari or Firefox

### ISSUE THREAD

**Issue by h8rry** [google/blockly-games#93]
https://blockly-games.appspot.com/maze?lang=en&level=6&skin=0

If you try the conditional block "if path to the left" in level 6, it's not working properly in Chrome, Safari or Firefox.

Note: you might want to try it in guest mode because of caching

**Comment by NeilFraser** [comment]
A new build was pushed a few minutes before this bug was filed.  I assume that the bug is gone now?

**Comment by h8rry** [comment]
Yes. Fixed! Thank you @NeilFraser
